feat(signup): implementa a página de 'signup'
po-ui/po-sample-conference pull request #7
Opened 2020-09-22 16:58 UTC by brunotz

Definidas a página de signup

Simulação:
Subir a API:

no repositório do projeto thf-conference-api (github - https://github.com/totvs/thf-conference-sample), dentro da pasta thf-conference-api, alterar o arquivo writer.js na linha 39: alterar de 'totvs_sync_date' para 'po-sync-date' e rodar o nodemon index.js ou npm run start.
APP:

git checkout sample-app/DTHFUI-3364
npm install
ionic serve
Teste: Comparar a funcionalidade com a funcionalidade existente no repositório antigo (onde está a api)

2020-09-23 13:44 UTC, samir-ayoub approved these changes, later dismissed

2020-09-23 17:31 UTC, nicoleoliveira requested changes
Depois que o usuário é criado, ele não aparece como logado na tela. 
Isso é possível identificar tentando favoritar um item

2020-09-24 14:51 UTC, nicoleoliveira approved these changes

2020-09-24 15:17 UTC, samir-ayoub approved these changes

2020-09-24 17:12 UTC, jhosefmarks approved these changes

2020-09-24 17:13 UTC, merged