feat(po-sample-web-conference): migra e atualiza sample web conference
po-ui/po-sample-conference pull request #8
Opened 2020-09-22 22:52 UTC by alinelariguet

**PO-SAMPLE-WEB-CONFERENCE**

**DTHFUI-3368**

Migra e atualiza o repositório do `po-sample-web-conference`.

2020-09-24 20:01 UTC, nicoleoliveira requested changes

2020-09-24 20:01 UTC, nicoleoliveira commented on po-sample-web-conference/src/app/speaker/speaker-card/speaker-card.component.html
> +</po-widget>
A rota da foto e do título não está funcionando, pode ser alterado no seguinte trecho:
```suggestion
<po-widget
  p-height="200"
  p-primary-label="Lectures"
  p-secondary-label="Edit"
  (p-primary-action)="detail()"
  (p-secondary-action)="edit()">

  <a [routerLink]="['detail/', speaker.id]">
    <po-avatar
      class="po-xl-4 po-lg-3"
      p-size="lg"
      p-src="../../assets/images/{{ speaker.photo }}">
    </po-avatar>
  </a>

  <div class="po-xl-8 po-lg-9 card-description">
    <a class="title-link" [routerLink]="['detail/', speaker.id]">
      <p class="po-font-text-large-bold">{{ speaker.name }}</p>
    </a>
    <p class="po-font-text">{{ speaker.email }}</p>
  </div>

</po-widget>
```

2020-09-24 20:01 UTC, nicoleoliveira commented on po-sample-web-conference/src/app/home/home-routing.module.ts
> +          { path: 'detail/:id', component: LectureEditComponent },
```suggestion
          { path: 'detail/:id', component: LectureDetailComponent },
```

2020-09-24 20:01 UTC, nicoleoliveira commented on po-sample-web-conference/src/app/home/home-routing.module.ts
> +          { path: 'detail/:id', component: SpeakerEditComponent },
```suggestion
          { path: 'detail/:id', component: SpeakerDetailComponent },
```

2020-09-24 20:10 UTC, samir-ayoub approved these changes, later dismissed

2020-09-24 20:47 UTC, nicoleoliveira requested changes

2020-09-24 20:47 UTC, nicoleoliveira commented on po-sample-web-conference/src/app/lecture/lecture.component.ts
> +    ngModel: 'lecture',
ngModel foi depreciado do PoPageFilter

2020-09-24 20:52 UTC, nicoleoliveira commented on po-sample-web-conference/src/app/lecture/lecture.component.ts
> +    ngModel: 'lecture',
e ao filtrar uma palestra não existente, não está aparecendo o trecho que notifica ao usuário que não encontrou o item.

2020-09-25 13:04 UTC, nicoleoliveira approved these changes

2020-09-25 13:11 UTC, samir-ayoub approved these changes

2020-09-25 13:35 UTC, jhosefmarks approved these changes

2020-09-25 13:35 UTC, merged